spring:
    datasource:
        url: jdbc:mysql://qtechdb-1.cexugk1h8rui.ap-northeast-1.rds.amazonaws.com:3306/spring_social
#        url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: admin
        password: F3v2vGWzb8vaniE3nqzi

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 407975209105-bqu6hq2d368hq48clc9dm57bchvk5r8o.apps.googleusercontent.com
              clientSecret: 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
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 723295919482479
              clientSecret: d4df528159c0f48626771136725cfb5c
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: d467cec5a9e0d47d431d
              clientSecret: 95e36de39fafcaedba526942544375a8530d6153
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
#          provider:
#            facebook:
#              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
#              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
#
#              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,https://qtech.space,https://api.qtech.space,http://localhost:8080,http://qtech-env.eba-h5rqqnbn.ap-northeast-1.elasticbeanstalk.com

  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - https://qtech.space/
      - https://qtech.space/oauth2/redirect
      - http://localhost:3000/oauth2/redirect
      - http://localhost:3000/
      - https://api.qtech.space
      - https://api.qtech.space/oauth2/redirect



      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect






server:
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto